version: '3.1'

services:

  smart-home-db:
    image: mysql
    restart: always
    ports:
      - "8888:3306"
    environment:
      MYSQL_DATABASE: smarthome
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
    volumes:
      - smarthome-db:/var/lib/mysql 
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8887:80"
    environment:
      - PMA_ARBITRARY=1
volumes:
  smarthome-db: 