CREATE USER c##demoadmim IDENTIFIED BY Geeks123 ;


CREATE USER c##ADMIN IDENTIFIED  BY Huyhoa2003;


GRANT CONNECT , RESOURCE  , DBA TO c##ADMIN

connect c##ADMIN@FREEPDB1


SHOW CON_NAME;

ALTER DATABASE OPEN;

ALTER SESSION SET CONTAINER = freeorcl;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CURRENT_PDB FROM DUAL;

ALTER SESSION SET CONTAINER = FREEPDB1;



SHOW PDBS;

SELECT * FROM DBA_PDBS WHERE PDB_NAME = 'PDBORCL';

CREATE PLUGGABLE DATABASE PDBORCL ADMIN USER pdbadmin IDENTIFIED BY Huyhoa2003;

