set serveroutput on;

CREATE TABLE person
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id)
)

INSERT INTO person VALUES (1 , 'HUYHOA');
select * from person;

DECLARE 
    TYPE strong_ref_cursor IS REF CURSOR RETURN person%ROWTYPE;
    v_cursor strong_ref_cursor;
    v_row person%ROWTYPE;
    
BEGIN
    OPEN v_cursor FOR SELECT * FROM person where id = 1;
    FETCH v_cursor INTO v_row;
    CLOSE v_cursor;
    
    dbms_output.put_line('The name of person with id = ' || v_row.id || ' is ' || v_row.name);
END;



/
declare
    type weak_ref_cursor is ref cursor;
    v_cursor weak_ref_cursor;
    v_id person.id%type;
    v_name person.name%type;
begin
    open v_cursor for select id, name from person where id = 1;
    fetch v_cursor into v_id, v_name;
    close v_cursor;
    
    dbms_output.put_line('The name of person with id = ' || v_id || ' is ' || v_name);
end;
/


/* SYS_REFCURSOR */
/
DECLARE 
    v_cursor sys_refcursor;
    v_id person.id%type;
    v_name person.name%type;

BEGIN
    OPEN v_cursor FOR SELECT id , name FROM person where id = 1;
    FETCH v_cursor INTO v_id , v_name;
    CLOSE v_cursor;
    dbms_output.put_line('The name of person with id = ' || v_id || ' is ' || v_name);
END;

/